import Image from "next/image";
import { getTranslations } from "next-intl/server";
import { Breadcrumbs } from "@/components/shared/breadcrumbs";
import { ButtonLink } from "@/components/ui/button";
import { Container } from "@/components/ui/container";
import { Section } from "@/components/ui/section";

export async function AboutPage() {
  const t = await getTranslations("aboutPage");

  return (
    <>
      <section className="border-b border-border bg-background"><Container className="py-10 sm:py-14 lg:py-16"><Breadcrumbs current={t("breadcrumb")} /><div className="mt-10 grid gap-10 lg:grid-cols-[0.95fr_1.05fr] lg:items-center lg:gap-16"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[0.16em] text-primary">{t("heroEyebrow")}</p><h1 className="mt-4 text-[2.7rem] font-semibold leading-[1.05] tracking-[-0.035em] text-navy sm:text-5xl lg:text-[3.8rem]">{t("heroTitle")}</h1><p className="mt-6 max-w-xl text-lg leading-8 text-muted">{t("heroDescription")}</p><ButtonLink href="/offerte" size="lg" className="mt-8">{t("quoteCta")}<span className="ml-2" aria-hidden="true">→</span></ButtonLink></div><figure className="relative min-h-[22rem] overflow-hidden rounded-2xl bg-navy sm:min-h-[31rem]"><Image src="/images/hero-cleaner-glass.jpg" alt={t("heroImageAlt")} fill priority sizes="(min-width: 1024px) 48vw, 100vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-navy/80 via-navy/10 to-transparent" aria-hidden="true" /><figcaption className="absolute inset-x-0 bottom-0 border-l-2 border-[#9fc0ff] px-6 py-5 text-base font-semibold text-white sm:px-8">{t("heroImageCaption")}</figcaption></figure></div></Container></section>
      <Section className="bg-surface"><Container className="grid gap-12 lg:grid-cols-[0.8fr_1.2fr] lg:gap-20"><div><p className="text-sm font-bold uppercase tracking-[0.16em] text-primary">{t("whoEyebrow")}</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-navy sm:text-4xl">{t("whoTitle")}</h2></div><div className="space-y-5 text-lg leading-8 text-muted"><p>{t("whoParagraphOne")}</p><p>{t("whoParagraphTwo")}</p></div></Container></Section>
      <Section className="bg-background"><Container><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[0.16em] text-primary">{t("workEyebrow")}</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-navy sm:text-4xl">{t("workTitle")}</h2><p className="mt-4 text-lg leading-8 text-muted">{t("workDescription")}</p></div><ol className="mt-10 grid gap-8 border-t border-border pt-8 sm:grid-cols-3">{(["scope", "communicate", "deliver"] as const).map((key, index)=><li key={key} className="border-t-2 border-primary pt-4"><span className="text-sm font-bold text-primary">0{index+1}</span><h3 className="mt-4 text-lg font-semibold text-navy">{t(`work.${key}.title`)}</h3><p className="mt-3 text-sm leading-7 text-muted">{t(`work.${key}.description`)}</p></li>)}</ol></Container></Section>
      <Section className="bg-[#eaf2ff]"><Container><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[0.16em] text-primary">{t("expectEyebrow")}</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-navy sm:text-4xl">{t("expectTitle")}</h2></div><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{(["homes", "businesses", "equipment", "area"] as const).map(key=><article key={key} className="bg-background p-6"><h3 className="text-lg font-semibold text-navy">{t(`expect.${key}.title`)}</h3><p className="mt-3 text-sm leading-7 text-muted">{t(`expect.${key}.description`)}</p></article>)}</div></Container></Section>
      <Section className="bg-navy text-white"><Container className="flex flex-col justify-between gap-8 lg:flex-row lg:items-end lg:gap-16"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[0.16em] text-[#9fc0ff]">{t("finalEyebrow")}</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">{t("finalTitle")}</h2><p className="mt-5 text-lg leading-8 text-white/70">{t("finalDescription")}</p></div><div className="flex flex-col gap-3 sm:flex-row"><ButtonLink href="/offerte" size="lg" className="w-full sm:w-auto">{t("quoteCta")}</ButtonLink><ButtonLink href="/contact" variant="outline" size="lg" className="w-full border-white/30 text-white hover:bg-white/10 sm:w-auto">{t("contactCta")}</ButtonLink></div></Container></Section>
    </>
  );
}
