import type { ServiceId } from "@/config/services";
import type { SupportedLocale } from "@/config/site";

type Copy = {
  title: string;
  metaTitle: string;
  metaDescription: string;
  eyebrow: string;
  intro: string;
  shortDescription: string;
  imageAlt: string;
  imageCaption: string;
  audienceTitle: string;
  areasTitle: string;
  approachTitle: string;
  approachDescription: string;
  scheduleTitle: string;
  scheduleDescription: string;
  featureEyebrow: string;
  featureTitle: string;
  featureDescription: string;
  equipmentTitle: string;
  equipmentDescription: string;
  productsNote: string;
  processTitle: string;
  processDescription: string;
  faqTitle: string;
  finalTitle: string;
};

const copy: Record<Extract<ServiceId, "school" | "home" | "deep" | "windows" | "postConstruction" | "move" | "airbnb" | "staircase">, Record<SupportedLocale, Copy>> = {
  school: {
    "nl-BE": { metaTitle: "Schoolschoonmaak Gent | Ster Schoonmaak", metaDescription: "Praktische schoolschoonmaak in Gent voor klaslokalen, gangen en gedeelde ruimtes. Bespreek uw planning en offerte op maat.", eyebrow: "Schoolschoonmaak in Gent", title: "Een verzorgde leeromgeving, ruimte na ruimte.", intro: "Schoonmaak voor scholen en onderwijsomgevingen in Gent en omgeving, afgestemd op de ruimtes, bezetting en planning van uw locatie.", shortDescription: "Voor scholen en onderwijsruimtes.", imageAlt: "Een helder, leeg klaslokaal met rijen tafels en stoelen.", imageCaption: "Praktische schoonmaak voor klaslokalen en gedeelde ruimtes.", audienceTitle: "Voor scholen met een eigen dagritme.", areasTitle: "Ruimtes volgens afgesproken scope.", approachTitle: "Schoonmaak rond de schoolwerking.", approachDescription: "We bespreken de lokalen, bezetting en momenten waarop schoonmaak praktisch kan gebeuren.", scheduleTitle: "Voor, na of rond de schooluren.", scheduleDescription: "Een terugkerende planning kan worden besproken volgens de werking van uw school en onze beschikbaarheid.", featureEyebrow: "Onderwijsomgeving", featureTitle: "Een nette basis voor elke schooldag.", featureDescription: "De focus ligt op de afgesproken lokalen, doorgangen en gedeelde ruimtes. Specialistische ontsmetting of certificering maakt geen deel uit van deze opdracht.", equipmentTitle: "Materiaal en producten", equipmentDescription: "Professioneel materiaal wordt gekozen voor de afgesproken ruimtes en taken.", productsNote: "Producten kunnen door Ster Schoonmaak of de klant worden voorzien, of samen worden afgesproken.", processTitle: "We starten met uw schoolplanning.", processDescription: "Bezorg ons de belangrijkste ruimtes, toegangsmomenten en gewenste frequentie. Daarna bepalen we samen de scope.", faqTitle: "Veelgestelde vragen over schoolschoonmaak.", finalTitle: "Bespreek een schoolplanning die werkt." },
    "en-BE": { metaTitle: "School cleaning Ghent | Ster Schoonmaak", metaDescription: "Practical school cleaning in Ghent for classrooms, corridors and shared areas. Discuss your schedule and tailored quote.", eyebrow: "School cleaning in Ghent", title: "A cared-for learning environment, room by room.", intro: "Cleaning for schools and educational environments in Ghent and surrounding areas, aligned with your spaces, occupancy and schedule.", shortDescription: "For schools and educational spaces.", imageAlt: "A bright, empty classroom with rows of desks and chairs.", imageCaption: "Practical cleaning for classrooms and shared spaces.", audienceTitle: "For schools with their own daily rhythm.", areasTitle: "Areas within the agreed scope.", approachTitle: "Cleaning around school operations.", approachDescription: "We discuss the rooms, occupancy and practical moments for cleaning at your location.", scheduleTitle: "Before, after or around school hours.", scheduleDescription: "A recurring schedule can be discussed according to your school's operation and our availability.", featureEyebrow: "Educational environment", featureTitle: "A clean foundation for every school day.", featureDescription: "The focus is on agreed rooms, passageways and shared spaces. Specialist disinfection or certification is not part of this assignment.", equipmentTitle: "Equipment and products", equipmentDescription: "Professional equipment is selected for the agreed areas and tasks.", productsNote: "Products can be supplied by Ster Schoonmaak or the client, or arranged together.", processTitle: "We start with your school schedule.", processDescription: "Share the main areas, access moments and desired frequency. We then define the scope together.", faqTitle: "Frequently asked questions about school cleaning.", finalTitle: "Discuss a school schedule that works." },
  },
  home: {
    "nl-BE": { metaTitle: "Woning schoonmaken Gent | Ster Schoonmaak", metaDescription: "Professionele woningschoonmaak in Gent voor woonkamers, keukens, badkamers en slaapkamers. Eenmalig of terugkerend, volgens afspraak.", eyebrow: "Woningschoonmaak in Gent", title: "Een frisse woning, volgens uw wensen.", intro: "Schoonmaak voor particuliere woningen en appartementen in Gent en omgeving, met aandacht voor de ruimtes die voor u belangrijk zijn.", shortDescription: "Voor woningen en appartementen.", imageAlt: "Een vrouw stofzuigt een lichte woonkamer.", imageCaption: "Aandacht voor de ruimtes die voor u belangrijk zijn.", audienceTitle: "Voor woningen die extra aandacht verdienen.", areasTitle: "Van leefruimte tot sanitair.", approachTitle: "Schoonmaak die bij uw woning past.", approachDescription: "We bespreken wat u gedaan wilt hebben, welke ruimtes prioriteit hebben en welke planning haalbaar is.", scheduleTitle: "Eenmalig of terugkerend.", scheduleDescription: "U kunt een eenmalige opdracht of een terugkerende planning bespreken, afhankelijk van uw vraag en onze beschikbaarheid.", featureEyebrow: "Particulier", featureTitle: "Schoonmaak voor uw woning, niet meer beloven dan dat.", featureDescription: "We richten ons op de afgesproken schoonmaaktaken. Persoonlijke verzorging, huishoudelijke begeleiding, dienstencheques of andere niet-schoonmaakdiensten behoren niet tot de opdracht.", equipmentTitle: "Materiaal en producten", equipmentDescription: "Professionele apparatuur wordt afgestemd op de woning en de afgesproken taken.", productsNote: "Producten kunnen door Ster Schoonmaak of de klant worden voorzien, of samen worden afgesproken.", processTitle: "Vertel wat er in uw woning nodig is.", processDescription: "Bespreek de ruimtes, prioriteiten en gewenste frequentie. Wanneer nodig bekijken we de woning ter plaatse.", faqTitle: "Veelgestelde vragen over woningschoonmaak.", finalTitle: "Maak uw woning klaar voor een frisse start." },
    "en-BE": { metaTitle: "Home cleaning Ghent | Ster Schoonmaak", metaDescription: "Professional home cleaning in Ghent for living rooms, kitchens, bathrooms and bedrooms. One-off or recurring, by agreement.", eyebrow: "Home cleaning in Ghent", title: "A fresh home, according to your priorities.", intro: "Cleaning for private homes and apartments in Ghent and surrounding areas, with attention to the rooms that matter to you.", shortDescription: "For homes and apartments.", imageAlt: "A woman vacuuming a bright living room.", imageCaption: "Attention to the rooms that matter to you.", audienceTitle: "For homes that need extra attention.", areasTitle: "From living spaces to bathrooms.", approachTitle: "Cleaning that fits your home.", approachDescription: "We discuss what you want cleaned, which rooms have priority and which schedule is practical.", scheduleTitle: "One-off or recurring.", scheduleDescription: "You can discuss a one-off assignment or recurring schedule, depending on your request and our availability.", featureEyebrow: "Residential", featureTitle: "Cleaning for your home, without promising more than that.", featureDescription: "We focus on agreed cleaning tasks. Personal care, household support, service vouchers and other non-cleaning services are not part of this assignment.", equipmentTitle: "Equipment and products", equipmentDescription: "Professional equipment is matched to the home and agreed tasks.", productsNote: "Products can be supplied by Ster Schoonmaak or the client, or arranged together.", processTitle: "Tell us what your home needs.", processDescription: "Discuss the areas, priorities and desired frequency. When needed, we view the home on site.", faqTitle: "Frequently asked questions about home cleaning.", finalTitle: "Prepare your home for a fresh start." },
  },
  deep: {
    "nl-BE": { metaTitle: "Grondige schoonmaak Gent | Ster Schoonmaak", metaDescription: "Grondige schoonmaak in Gent voor woningen, kantoren en andere ruimtes die extra aandacht nodig hebben. Bespreek de scope en planning.", eyebrow: "Grondige schoonmaak in Gent", title: "Extra aandacht voor een ruimte die opnieuw moet ademen.", intro: "Een grondige schoonmaak voor woningen, kantoren en andere ruimtes die meer nodig hebben dan het gewone onderhoud.", shortDescription: "Voor een grondige opfrisbeurt.", imageAlt: "Een medewerker stofzuigt een stoffen zetel in een moderne ruimte.", imageCaption: "Extra aandacht voor oppervlakken en details.", audienceTitle: "Voor ruimtes met een duidelijke resetvraag.", areasTitle: "Details binnen de afgesproken scope.", approachTitle: "Grondig, maar helder afgebakend.", approachDescription: "We bepalen vooraf welke ruimtes en details extra aandacht krijgen, zodat de opdracht realistisch en controleerbaar blijft.", scheduleTitle: "Wanneer een grondige beurt past.", scheduleDescription: "Een eenmalige, periodieke of voorbereidende grondige schoonmaak kan worden besproken volgens uw situatie.", featureEyebrow: "Afbakening", featureTitle: "Dieper reinigen zonder specialistische claims.", featureDescription: "Deze dienst gaat verder dan standaardonderhoud, maar omvat geen sterilisatie, medische sanering, asbest, biohazard, schimmelbestrijding of andere gevaarlijke decontaminatie.", equipmentTitle: "Materiaal en producten", equipmentDescription: "We stemmen professioneel materiaal af op de ruimte, ondergrond en afgesproken taken.", productsNote: "Producten kunnen door Ster Schoonmaak of de klant worden voorzien, of samen worden afgesproken.", processTitle: "Een grondige opdracht begint met de juiste scope.", processDescription: "Deel welke ruimtes extra aandacht vragen en waarom. Daarna bespreken we de praktische aanpak en timing.", faqTitle: "Veelgestelde vragen over grondige schoonmaak.", finalTitle: "Bespreek de grondige aanpak van uw ruimte." },
    "en-BE": { metaTitle: "Deep cleaning Ghent | Ster Schoonmaak", metaDescription: "Deep cleaning in Ghent for homes, offices and other spaces needing extra attention. Discuss the scope and schedule.", eyebrow: "Deep cleaning in Ghent", title: "Extra attention for a space that needs a reset.", intro: "Deep cleaning for homes, offices and other spaces that need more than routine maintenance.", shortDescription: "For a thorough refresh.", imageAlt: "A cleaner vacuums a fabric sofa in a modern room.", imageCaption: "Extra attention for surfaces and details.", audienceTitle: "For spaces with a clear reset need.", areasTitle: "Details within the agreed scope.", approachTitle: "Thorough, but clearly defined.", approachDescription: "We agree in advance which areas and details need extra attention, keeping the assignment realistic and clear.", scheduleTitle: "When a deep clean fits.", scheduleDescription: "A one-off, periodic or pre-event deep clean can be discussed according to your situation.", featureEyebrow: "Clear boundaries", featureTitle: "A deeper clean without specialist claims.", featureDescription: "This service goes beyond routine maintenance, but does not include sterilisation, medical sanitation, asbestos, biohazards, mould remediation or other hazardous decontamination.", equipmentTitle: "Equipment and products", equipmentDescription: "We match professional equipment to the space, surfaces and agreed tasks.", productsNote: "Products can be supplied by Ster Schoonmaak or the client, or arranged together.", processTitle: "A deep assignment starts with the right scope.", processDescription: "Share which areas need extra attention and why. We then discuss the practical approach and timing.", faqTitle: "Frequently asked questions about deep cleaning.", finalTitle: "Discuss the deep approach for your space." },
  },
  windows: {
    "nl-BE": { metaTitle: "Ramenreiniging Gent | Ster Schoonmaak", metaDescription: "Ramenreiniging in Gent voor bereikbare ramen, glaspartijen, kozijnen en vensterbanken. Eenmalig of terugkerend volgens afspraak.", eyebrow: "Ramenreiniging in Gent", title: "Helder glas, zorgvuldig bereikbaar.", intro: "Ramen en glaspartijen schoonmaken voor woningen, kantoren en commerciële ruimtes, met focus op wat veilig en praktisch bereikbaar is.", shortDescription: "Voor ramen en bereikbare glaspartijen.", imageAlt: "Een vrouw maakt een raam schoon met glasreiniger.", imageCaption: "Heldere ramen met aandacht voor veilige bereikbaarheid.", audienceTitle: "Voor panden met bereikbare glaspartijen.", areasTitle: "Glas en de directe afwerking.", approachTitle: "Veilig en praktisch gepland.", approachDescription: "We bespreken welke ramen bereikbaar zijn, welke zijde nodig is en welke hulpmiddelen passend zijn voor de opdracht.", scheduleTitle: "Eenmalig, terugkerend of seizoensgebonden.", scheduleDescription: "Ramenreiniging kan eenmalig, periodiek of volgens een seizoensplanning worden besproken.", featureEyebrow: "Veilige afbakening", featureTitle: "Heldere ramen zonder risicovolle bereikbaarheid.", featureDescription: "We werken aan ramen die veilig bereikbaar zijn. Touwtechnieken, hoogbouw, hoogwerkers en andere specialistische toegang behoren niet tot deze dienst.", equipmentTitle: "Materiaal en producten", equipmentDescription: "Professioneel materiaal wordt afgestemd op glas, kaders en de bereikbaarheid ter plaatse.", productsNote: "Producten kunnen door Ster Schoonmaak of de klant worden voorzien, of samen worden afgesproken.", processTitle: "We brengen eerst de bereikbaarheid in kaart.", processDescription: "Bezorg ons informatie over het pand, de ramen en de gewenste zijde. Indien nodig bekijken we de situatie ter plaatse.", faqTitle: "Veelgestelde vragen over ramenreiniging.", finalTitle: "Bespreek een heldere ramenopdracht." },
    "en-BE": { metaTitle: "Window cleaning Ghent | Ster Schoonmaak", metaDescription: "Window cleaning in Ghent for accessible windows, glass panels, frames and sills. One-off or recurring by agreement.", eyebrow: "Window cleaning in Ghent", title: "Clear glass, safely reachable.", intro: "Window and glass cleaning for homes, offices and commercial spaces, focused on what is safe and practical to reach.", shortDescription: "For windows and accessible glass.", imageAlt: "A woman cleaning a window with glass cleaner.", imageCaption: "Clear windows with attention to safe access.", audienceTitle: "For properties with accessible glass.", areasTitle: "Glass and its immediate finish.", approachTitle: "Safely and practically scheduled.", approachDescription: "We discuss which windows are reachable, which side is needed and which equipment suits the assignment.", scheduleTitle: "One-off, recurring or seasonal.", scheduleDescription: "Window cleaning can be discussed as a one-off, periodic or seasonal arrangement.", featureEyebrow: "Safe boundaries", featureTitle: "Clear windows without risky access.", featureDescription: "We work on safely reachable windows. Rope access, high-rise work, aerial platforms and other specialist access are outside this service.", equipmentTitle: "Equipment and products", equipmentDescription: "Professional equipment is matched to glass, frames and on-site accessibility.", productsNote: "Products can be supplied by Ster Schoonmaak or the client, or arranged together.", processTitle: "We first understand accessibility.", processDescription: "Share information about the property, windows and desired sides. If needed, we view the situation on site.", faqTitle: "Frequently asked questions about window cleaning.", finalTitle: "Discuss a clear window-cleaning assignment." },
  },
  postConstruction: {
    "nl-BE": { metaTitle: "Opleveringsschoonmaak Gent | Ster Schoonmaak", metaDescription: "Opleveringsschoonmaak in Gent na bouw- of renovatiewerken: stof, vloeren, oppervlakken en ramen volgens een duidelijke scope.", eyebrow: "Opleveringsschoonmaak in Gent", title: "Van werken naar een verzorgde ruimte.", intro: "Schoonmaak na bouw- of renovatiewerken voor woningen, commerciële panden en andere ruimtes die klaar moeten worden gemaakt voor gebruik.", shortDescription: "Voor schoonmaak na bouw- of renovatiewerken.", imageAlt: "Een stofzuiger staat in een lichte ruimte die wordt gerenoveerd.", imageCaption: "Stof en bouwresten aanpakken volgens afspraak.", audienceTitle: "Voor een pand na werken.", areasTitle: "De zichtbare sporen van de werken.", approachTitle: "Een duidelijke scope na de werken.", approachDescription: "We bekijken welke ruimtes klaar zijn voor schoonmaak en spreken af welke stof, resten en oppervlakken worden opgenomen.", scheduleTitle: "Na de werken, eenmalig of in stappen.", scheduleDescription: "Een opleveringsschoonmaak kan eenmalig of gefaseerd worden gepland wanneer ruimtes op verschillende momenten beschikbaar zijn.", featureEyebrow: "Veilige afbakening", featureTitle: "Stofvrij werken binnen een normale schoonmaakscope.", featureDescription: "We pakken standaard bouwstof en afgesproken resten aan. Asbest, gevaarlijk afval, industriële reiniging en specialistische afvalverwerking vallen buiten de dienst.", equipmentTitle: "Materiaal en producten", equipmentDescription: "We gebruiken professioneel materiaal dat past bij de afgesproken ondergronden en werkzaamheden.", productsNote: "Producten kunnen door Ster Schoonmaak of de klant worden voorzien, of samen worden afgesproken.", processTitle: "Eerst weten wat klaar is voor schoonmaak.", processDescription: "Deel de stand van de werken, de ruimtes en de gewenste timing. Daarna maken we de scope en offerte concreet.", faqTitle: "Veelgestelde vragen over opleveringsschoonmaak.", finalTitle: "Maak uw pand klaar voor de volgende stap." },
    "en-BE": { metaTitle: "Post-construction cleaning Ghent | Ster Schoonmaak", metaDescription: "Post-construction cleaning in Ghent after building or renovation work: dust, floors, surfaces and accessible windows within a clear scope.", eyebrow: "Post-construction cleaning in Ghent", title: "From works to a cared-for space.", intro: "Cleaning after building or renovation work for homes, commercial properties and other spaces being prepared for use.", shortDescription: "For cleaning after building or renovation work.", imageAlt: "A vacuum cleaner stands in a bright room under renovation.", imageCaption: "Addressing dust and construction residue by agreement.", audienceTitle: "For a property after works.", areasTitle: "Visible traces of the works.", approachTitle: "A clear scope after the works.", approachDescription: "We review which areas are ready for cleaning and agree which dust, residue and surfaces are included.", scheduleTitle: "After the works, once or in stages.", scheduleDescription: "Post-construction cleaning can be planned as one assignment or in stages when rooms become available at different times.", featureEyebrow: "Safe boundaries", featureTitle: "Working within a normal cleaning scope.", featureDescription: "We address standard construction dust and agreed residue. Asbestos, hazardous waste, industrial cleaning and specialist waste disposal are outside this service.", equipmentTitle: "Equipment and products", equipmentDescription: "We use professional equipment suited to the agreed surfaces and work.", productsNote: "Products can be supplied by Ster Schoonmaak or the client, or arranged together.", processTitle: "First establish what is ready to clean.", processDescription: "Share the status of the works, areas and desired timing. We then make the scope and quote concrete.", faqTitle: "Frequently asked questions about post-construction cleaning.", finalTitle: "Prepare your property for the next step." },
  },
  move: {
    "nl-BE": { metaTitle: "Verhuisschoonmaak Gent | Ster Schoonmaak", metaDescription: "Verhuisschoonmaak in Gent voor woningen en appartementen: vloeren, keukens, badkamers, oppervlakken en bereikbare ramen volgens afspraak.", eyebrow: "Verhuisschoonmaak in Gent", title: "Een frisse start of een nette oplevering.", intro: "Schoonmaak vóór een verhuis, na het leeghalen of tussen twee bewoners, met een duidelijke scope voor de woning of het appartement.", shortDescription: "Voor verhuis- en oplevermomenten.", imageAlt: "Verhuisdozen staan klaar in een lichte woning.", imageCaption: "Een woning voorbereiden op de volgende stap.", audienceTitle: "Voor wie een woning overdraagt of betrekt.", areasTitle: "De basis voor een lege of nieuwe start.", approachTitle: "Rond het verhuis-moment.", approachDescription: "We bespreken of de woning leeg is, welke ruimtes prioriteit hebben en wanneer toegang mogelijk is.", scheduleTitle: "Voor, na of tussen twee bewoners.", scheduleDescription: "Een opdracht kan vóór de verhuis, na het leeghalen of tussen twee bewoners worden gepland volgens beschikbaarheid.", featureEyebrow: "Heldere scope", featureTitle: "Schoonmaken voor de volgende bewoner.", featureDescription: "We focussen op schoonmaak. Schadeherstel, schilderwerken, inspecties en garanties rond een huurwaarborg maken geen deel uit van deze dienst.", equipmentTitle: "Materiaal en producten", equipmentDescription: "We gebruiken professioneel materiaal voor de afgesproken ruimtes en ondergronden.", productsNote: "Producten kunnen door Ster Schoonmaak of de klant worden voorzien, of samen worden afgesproken.", processTitle: "Vertel wanneer de woning klaar is.", processDescription: "Bezorg ons de locatie, de staat van de woning en het gewenste moment. Dan bekijken we de opdracht en planning.", faqTitle: "Veelgestelde vragen over verhuisschoonmaak.", finalTitle: "Geef de volgende bewoner een frisse start." },
    "en-BE": { metaTitle: "Move-in / move-out cleaning Ghent | Ster Schoonmaak", metaDescription: "Move-in and move-out cleaning in Ghent for homes and apartments: floors, kitchens, bathrooms, surfaces and accessible windows by agreement.", eyebrow: "Move-in / move-out cleaning in Ghent", title: "A fresh start or a tidy handover.", intro: "Cleaning before a move, after emptying a property or between residents, with a clear scope for the home or apartment.", shortDescription: "For moving and handover moments.", imageAlt: "Moving boxes are ready in a bright home.", imageCaption: "Preparing a home for its next step.", audienceTitle: "For people handing over or moving into a home.", areasTitle: "The basis for an empty or fresh start.", approachTitle: "Around the moving moment.", approachDescription: "We discuss whether the property is empty, which areas have priority and when access is possible.", scheduleTitle: "Before, after or between residents.", scheduleDescription: "An assignment can be scheduled before the move, after emptying or between residents, subject to availability.", featureEyebrow: "Clear scope", featureTitle: "Cleaning for the next resident.", featureDescription: "We focus on cleaning. Repairs, painting, inspections and guarantees regarding a rental deposit are not part of this service.", equipmentTitle: "Equipment and products", equipmentDescription: "We use professional equipment for the agreed areas and surfaces.", productsNote: "Products can be supplied by Ster Schoonmaak or the client, or arranged together.", processTitle: "Tell us when the property is ready.", processDescription: "Share the location, condition and desired timing. We then review the assignment and schedule.", faqTitle: "Frequently asked questions about move-in / move-out cleaning.", finalTitle: "Give the next resident a fresh start." },
  },
  airbnb: {
    "nl-BE": { metaTitle: "Airbnb schoonmaak Gent | Ster Schoonmaak", metaDescription: "Airbnb schoonmaak in Gent tussen verblijven, voor appartementen en korte verblijven. Duidelijke scope, planning en offerte volgens beschikbaarheid.", eyebrow: "Airbnb schoonmaak in Gent", title: "Een verzorgde ruimte tussen verblijven.", intro: "Schoonmaak voor appartementen en korte verblijven in Gent en omgeving, volgens de afgesproken ruimtes en planning.", shortDescription: "Voor appartementen en korte verblijven.", imageAlt: "Een licht en modern appartement met bed en keuken.", imageCaption: "Een verzorgde ruimte volgens de afgesproken scope.", audienceTitle: "Voor hosts en korte verblijven.", areasTitle: "De ruimtes die gasten gebruiken.", approachTitle: "Duidelijk tussen twee verblijven.", approachDescription: "We bespreken de ruimtes, de gewenste timing en de manier waarop toegang tot het verblijf wordt geregeld.", scheduleTitle: "Volgens planning en beschikbaarheid.", scheduleDescription: "Schoonmaak tussen verblijven of volgens een terugkerend schema kan worden besproken, altijd volgens beschikbaarheid.", featureEyebrow: "Alleen schoonmaak", featureTitle: "Een nette basis voor het volgende verblijf.", featureDescription: "Deze dienst gaat over schoonmaak. Linnengoed, wassen, handdoeken, toiletartikelen, sleutelbeheer, gastencommunicatie en boekingsbeheer zijn niet inbegrepen.", equipmentTitle: "Materiaal en producten", equipmentDescription: "We gebruiken professioneel materiaal voor de afgesproken ruimtes en ondergronden.", productsNote: "Producten kunnen door Ster Schoonmaak of de klant worden voorzien, of samen worden afgesproken.", processTitle: "Maak de turnover concreet.", processDescription: "Deel de locatie, ruimtes, toegang en gewenste planning. Daarna bespreken we wat praktisch haalbaar is.", faqTitle: "Veelgestelde vragen over Airbnb schoonmaak.", finalTitle: "Bespreek uw schoonmaak tussen verblijven." },
    "en-BE": { metaTitle: "Airbnb cleaning Ghent | Ster Schoonmaak", metaDescription: "Airbnb cleaning in Ghent between stays for apartments and short stays. Clear scope, schedule and quote subject to availability.", eyebrow: "Airbnb cleaning in Ghent", title: "A cared-for space between stays.", intro: "Cleaning for apartments and short stays in Ghent and surrounding areas, according to the agreed areas and schedule.", shortDescription: "For apartments and short stays.", imageAlt: "A bright modern apartment with a bed and kitchen.", imageCaption: "A cared-for space within the agreed scope.", audienceTitle: "For hosts and short stays.", areasTitle: "The areas guests use.", approachTitle: "Clear between two stays.", approachDescription: "We discuss the areas, desired timing and how access to the accommodation is arranged.", scheduleTitle: "According to schedule and availability.", scheduleDescription: "Cleaning between stays or on a recurring schedule can be discussed, always subject to availability.", featureEyebrow: "Cleaning only", featureTitle: "A tidy foundation for the next stay.", featureDescription: "This service covers cleaning. Linen, laundry, towels, toiletries, key handling, guest communication and booking management are not included.", equipmentTitle: "Equipment and products", equipmentDescription: "We use professional equipment for the agreed areas and surfaces.", productsNote: "Products can be supplied by Ster Schoonmaak or the client, or arranged together.", processTitle: "Make the turnover concrete.", processDescription: "Share the location, areas, access and desired schedule. We then discuss what is practical.", faqTitle: "Frequently asked questions about Airbnb cleaning.", finalTitle: "Discuss your cleaning between stays." },
  },
  staircase: {
    "nl-BE": { metaTitle: "Trappenhal schoonmaak Gent | Ster Schoonmaak", metaDescription: "Schoonmaak van trappenhallen en gemeenschappelijke delen in Gent voor appartementsgebouwen en gedeelde panden. Volgens afspraak en planning.", eyebrow: "Trappenhal schoonmaak in Gent", title: "Verzorgde gemeenschappelijke doorgangen.", intro: "Terugkerende schoonmaak voor trappenhallen, gangen en andere gemeenschappelijke delen van appartementsgebouwen en gedeelde panden.", shortDescription: "Voor trappenhallen en gemeenschappelijke delen.", imageAlt: "Een medewerker maakt een trap schoon in een modern gebouw.", imageCaption: "Aandacht voor gedeelde doorgangen en trappen.", audienceTitle: "Voor gedeelde gebouwen.", areasTitle: "Van ingang tot trappenhal.", approachTitle: "Een vaste, overzichtelijke routine.", approachDescription: "We leggen vast welke gemeenschappelijke delen bij de opdracht horen en hoe vaak ze worden schoongemaakt.", scheduleTitle: "Terugkerend volgens uw gebouw.", scheduleDescription: "Wekelijkse of meermaals wekelijkse schoonmaak kan worden besproken volgens het gebruik en de praktische planning.", featureEyebrow: "Gemeenschappelijke delen", featureTitle: "Een nette route door het gebouw.", featureDescription: "We richten ons op de afgesproken trappenhallen, gangen en gedeelde delen. De scope en frequentie worden per gebouw bepaald; er zijn geen vaste pakketten.", equipmentTitle: "Materiaal en producten", equipmentDescription: "We werken met professioneel materiaal dat past bij de ondergronden en afgesproken zones.", productsNote: "Producten kunnen door Ster Schoonmaak of de klant worden voorzien, of samen worden afgesproken.", processTitle: "Start met de zones van uw gebouw.", processDescription: "Bezorg ons de gemeenschappelijke delen, toegang en gewenste frequentie. Daarna bespreken we de praktische scope.", faqTitle: "Veelgestelde vragen over trappenhal schoonmaak.", finalTitle: "Bespreek een verzorgde trappenhal." },
    "en-BE": { metaTitle: "Staircase and common-area cleaning Ghent | Ster Schoonmaak", metaDescription: "Staircase and common-area cleaning in Ghent for apartment buildings and shared properties. By agreement and schedule.", eyebrow: "Staircase and common-area cleaning in Ghent", title: "Cared-for shared passageways.", intro: "Recurring cleaning for staircases, corridors and other common areas in apartment buildings and shared properties.", shortDescription: "For staircases and common areas.", imageAlt: "A cleaner works on stairs in a modern building.", imageCaption: "Attention to shared passageways and staircases.", audienceTitle: "For shared buildings.", areasTitle: "From entrance to staircase.", approachTitle: "A consistent, clear routine.", approachDescription: "We define which common areas belong to the assignment and how often they are cleaned.", scheduleTitle: "According to your building.", scheduleDescription: "Weekly or multiple-times-per-week cleaning can be discussed according to use and practical planning.", featureEyebrow: "Common areas", featureTitle: "A tidy route through the building.", featureDescription: "We focus on agreed staircases, corridors and shared areas. Scope and frequency are set per building; there are no fixed packages.", equipmentTitle: "Equipment and products", equipmentDescription: "We work with professional equipment suited to the surfaces and agreed zones.", productsNote: "Products can be supplied by Ster Schoonmaak or the client, or arranged together.", processTitle: "Start with your building zones.", processDescription: "Share the common areas, access and desired frequency. We then discuss the practical scope.", faqTitle: "Frequently asked questions about staircase cleaning.", finalTitle: "Discuss a cared-for staircase." },
  },
};

const labels: Record<SupportedLocale, Record<string, string>> = {
  "nl-BE": { schools: "Scholen", educational: "Onderwijsomgevingen", learning: "Klaslokalen en leerplekken", administrative: "Administratieve schoolruimtes", houses: "Huizen", apartments: "Appartementen", residential: "Residentiële opdrachten", homes: "Woningen", offices: "Kantoren", commercial: "Commerciële ruimtes", reset: "Ruimtes na een intensieve periode", accessible: "Veilig bereikbare ramen", newProperties: "Nieuwe woningen en panden", renovations: "Renovaties", contractors: "Aannemers en bouwpartners", residentialOwners: "Eigenaars en bewoners", tenants: "Huurders", owners: "Eigenaars", landlords: "Verhuurders", hosts: "Airbnb-hosts", shortStay: "Korte verblijven", apartmentBuildings: "Appartementsgebouwen", propertyCompanies: "Vastgoed- en gebouwbeheerders", residentialBuildings: "Residentiële gebouwen", commercialShared: "Commerciële gedeelde panden", classrooms: "Klaslokalen", corridors: "Gangen en doorgangen", entrances: "Ingangen", staffRooms: "Personeelsruimtes", sanitary: "Sanitaire ruimtes", common: "Gedeelde ruimtes", floors: "Vloeren", living: "Woonkamers en leefruimtes", kitchens: "Keukens", bathrooms: "Badkamers", bedrooms: "Slaapkamers", surfaces: "Oppervlakken", edges: "Randen en details", glass: "Glaspartijen", interior: "Binnenzijde van ramen", exterior: "Buitenzijde wanneer veilig bereikbaar", frames: "Kozijnen en raamkaders", sills: "Vensterbanken", dust: "Bouwstof", residue: "Standaardresten volgens afspraak", cupboards: "Kasten wanneer afgesproken", staircases: "Trappen", landings: "Verdiepingsbordessen", lifts: "Liftruimtes wanneer afgesproken", handrails: "Leuningen" },
  "en-BE": { schools: "Schools", educational: "Educational environments", learning: "Classrooms and learning spaces", administrative: "Administrative school areas", houses: "Houses", apartments: "Apartments", residential: "Residential assignments", homes: "Homes", offices: "Offices", commercial: "Commercial spaces", reset: "Spaces after an intensive period", accessible: "Safely reachable windows", newProperties: "New homes and properties", renovations: "Renovations", contractors: "Contractors and building partners", residentialOwners: "Owners and residents", tenants: "Tenants", owners: "Owners", landlords: "Landlords", hosts: "Airbnb hosts", shortStay: "Short stays", apartmentBuildings: "Apartment buildings", propertyCompanies: "Property and building managers", residentialBuildings: "Residential buildings", commercialShared: "Commercial shared properties", classrooms: "Classrooms", corridors: "Corridors and passageways", entrances: "Entrances", staffRooms: "Staff rooms", sanitary: "Sanitary areas", common: "Shared areas", floors: "Floors", living: "Living spaces", kitchens: "Kitchens", bathrooms: "Bathrooms", bedrooms: "Bedrooms", surfaces: "Surfaces", edges: "Edges and details", glass: "Glass panels", interior: "Interior window surfaces", exterior: "Exterior surfaces when safely reachable", frames: "Frames and window surrounds", sills: "Window sills", dust: "Construction dust", residue: "Standard residue by agreement", cupboards: "Cupboards when agreed", staircases: "Staircases", landings: "Landings", lifts: "Lift areas when agreed", handrails: "Handrails" },
};

const scheduleLabels: Record<SupportedLocale, Record<string, string>> = {
  "nl-BE": { outsideHours: "Voor of na de schooluren", recurring: "Terugkerende schoonmaak", several: "Meerdere momenten per week", custom: "Planning op maat", oneTime: "Eenmalige opdracht", deep: "Grondige opfrisbeurt", periodic: "Periodieke opfrisbeurt", beforeEvent: "Voor een evenement of gebruiksmoment", seasonal: "Seizoensgebonden afspraak", afterWorks: "Na afronding van de werken", staged: "Gefaseerd per ruimte", beforeMove: "Voor de verhuis", afterMove: "Na het leeghalen", emptyProperty: "Lege woning of appartement", betweenStays: "Tussen twee verblijven", flexible: "Flexibele afspraak", weekly: "Wekelijkse schoonmaak" },
  "en-BE": { outsideHours: "Before or after school hours", recurring: "Recurring cleaning", several: "Several moments per week", custom: "Tailored schedule", oneTime: "One-off assignment", deep: "Deep refresh", periodic: "Periodic refresh", beforeEvent: "Before an event or use moment", seasonal: "Seasonal arrangement", afterWorks: "After the works are finished", staged: "Staged by area", beforeMove: "Before the move", afterMove: "After emptying", emptyProperty: "Empty home or apartment", betweenStays: "Between two stays", flexible: "Flexible arrangement", weekly: "Weekly cleaning" },
};

const faqQuestions: Record<SupportedLocale, Record<string, string>> = {
  "nl-BE": { hours: "Kan de schoonmaak buiten de normale uren gebeuren?", recurring: "Kunnen vaste of terugkerende momenten worden afgesproken?", areas: "Welke ruimtes kunnen worden opgenomen?", products: "Voorzien jullie de schoonmaakproducten?", pricing: "Hoe wordt de offerte bepaald?", scope: "Welke taken vallen binnen de scope?", oneTime: "Kan ik een eenmalige opdracht aanvragen?", care: "Bieden jullie ook huishoudelijke of persoonlijke hulp?", difference: "Wat is het verschil met gewone schoonmaak?", contexts: "Voor welke situaties is dit geschikt?", hazards: "Nemen jullie gevaarlijke stoffen of specialistisch afval mee?", insideOutside: "Kunnen binnen- en buitenzijde worden gedaan?", highRise: "Doen jullie hoogbouw of touwtechnieken?", frames: "Worden kozijnen en vensterbanken meegenomen?", residue: "Welke resten kunnen worden meegenomen?", windows: "Kunnen ramen worden opgenomen?", timing: "Wanneer kan de schoonmaak plaatsvinden?", deposit: "Garanderen jullie de teruggave van een huurwaarborg?", linen: "Doen jullie ook linnen of was?", turnover: "Kunnen jullie eenzelfde-dag-wissel beloven?", frequency: "Hoe vaak kan deze ruimte worden schoongemaakt?", handrails: "Worden leuningen meegenomen?", custom: "Werken jullie met vaste pakketten?" },
  "en-BE": { hours: "Can cleaning happen outside normal hours?", recurring: "Can fixed or recurring times be arranged?", areas: "Which areas can be included?", products: "Do you provide cleaning products?", pricing: "How is the quote determined?", scope: "Which tasks fall within the scope?", oneTime: "Can I request a one-off assignment?", care: "Do you also provide household or personal support?", difference: "How is this different from routine cleaning?", contexts: "Which situations suit this service?", hazards: "Do you handle hazardous substances or specialist waste?", insideOutside: "Can both interior and exterior sides be done?", highRise: "Do you handle high-rise or rope access?", frames: "Are frames and sills included?", residue: "Which residue can be included?", windows: "Can windows be included?", timing: "When can the cleaning take place?", deposit: "Do you guarantee the return of a rental deposit?", linen: "Do you also handle linen or laundry?", turnover: "Can you promise a same-day turnover?", frequency: "How often can this area be cleaned?", handrails: "Are handrails included?", custom: "Do you work with fixed packages?" },
};

export function getServiceFallbackValue(serviceId: ServiceId, locale: SupportedLocale, path: string): string | undefined {
  const target = path.match(/^items\.([^.]+)\.(.+)$/);
  const targetId = (target?.[1] ?? serviceId) as keyof typeof copy;
  const serviceCopy = copy[targetId]?.[locale];
  if (!serviceCopy || !target) return undefined;
  const rest = target[2];
  if (rest in serviceCopy) return serviceCopy[rest as keyof Copy];
  const audience = rest.match(/^audience\.(.+)$/);
  if (audience) return labels[locale][audience[1]] ?? audience[1];
  const area = rest.match(/^areas\.(.+)$/);
  if (area) return labels[locale][area[1]] ?? area[1];
  const schedule = rest.match(/^schedules\.(.+)$/);
  if (schedule) return scheduleLabels[locale][schedule[1]] ?? schedule[1];
  const point = rest.match(/^approachPoints\.(scope|communication|equipment)\.(title|description)$/);
  if (point) {
    const pointCopy = {
      "nl-BE": {
        scope: { title: "Duidelijke scope", description: "We spreken vooraf af welke ruimtes en taken bij de opdracht horen." },
        communication: { title: "Heldere afstemming", description: "Timing, toegang en aandachtspunten worden vooraf praktisch besproken." },
        equipment: { title: "Passend materiaal", description: "Professioneel materiaal wordt afgestemd op de afgesproken ruimtes en ondergronden." },
      },
      "en-BE": {
        scope: { title: "Clear scope", description: "We agree in advance which areas and tasks belong to the assignment." },
        communication: { title: "Clear alignment", description: "Timing, access and points of attention are discussed practically in advance." },
        equipment: { title: "Suitable equipment", description: "Professional equipment is matched to the agreed areas and surfaces." },
      },
    } as const;
    const pointId = point[1] as "scope" | "communication" | "equipment";
    const field = point[2] as "title" | "description";
    return pointCopy[locale][pointId][field];
  }
  const faq = rest.match(/^faqs\.(.+)\.(question|answer)$/);
  if (faq) {
    if (faq[2] === "question") return faqQuestions[locale][faq[1]] ?? faq[1];
    const boundary = faq[1];
    if (locale === "nl-BE") {
      if (boundary === "hazards") return "Nee. Gevaarlijke stoffen, asbest, biohazard en specialistische afvalverwerking vallen buiten deze dienst.";
      if (boundary === "highRise") return "Nee. Hoogbouw, touwtechnieken en toegang met hoogwerkers vallen buiten deze dienst.";
      if (boundary === "deposit") return "Nee. We geven geen garantie over een huurwaarborg of inspectieresultaat.";
      if (boundary === "care") return "Nee. Ster Schoonmaak richt zich op schoonmaak; persoonlijke verzorging en huishoudelijke begeleiding maken geen deel uit van deze dienst.";
      if (boundary === "linen") return "Nee. Linnengoed, wassen, handdoeken en toiletartikelen vallen buiten deze schoonmaakdienst.";
      if (boundary === "turnover") return "Nee. Timing wordt per opdracht en volgens beschikbaarheid afgesproken; een vaste same-day-belofte doen we niet.";
      return "Dat kan worden besproken volgens de ruimtes, taken, toegang en planning van uw opdracht.";
    }
    if (boundary === "hazards") return "No. Hazardous substances, asbestos, biohazards and specialist waste disposal are outside this service.";
    if (boundary === "highRise") return "No. High-rise work, rope access and aerial-platform access are outside this service.";
    if (boundary === "deposit") return "No. We do not guarantee a rental deposit or inspection result.";
    if (boundary === "care") return "No. Ster Schoonmaak focuses on cleaning; personal care and household support are not part of this service.";
    if (boundary === "linen") return "No. Linen, laundry, towels and toiletries are outside this cleaning service.";
    if (boundary === "turnover") return "No. Timing is agreed per assignment and subject to availability; we do not make a fixed same-day promise.";
    return "This can be discussed according to the areas, tasks, access and schedule of your assignment.";
  }
  return undefined;
}
