"use client";

import { FormEvent, useState } from "react";
import { useLocale } from "next-intl";
import { createComplaint } from "@/lib/backoffice-api";

export function ComplaintForm() {
  const locale = useLocale(); const english = locale === "en-BE"; const [values, setValues] = useState({ customerName: "", customerEmail: "", customerPhone: "", subject: "", message: "", website: "" }); const [busy, setBusy] = useState(false); const [result, setResult] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const set = (key: string, value: string) => setValues((current) => ({ ...current, [key]: value }));
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(null); setResult(null); try { const response = await createComplaint(values, locale, window.location.pathname); setResult(`${english ? "Thank you. Your complaint reference is" : "Bedankt. Uw klachtreferentie is"} ${response.reference}.`); setValues({ customerName: "", customerEmail: "", customerPhone: "", subject: "", message: "", website: "" }); } catch (caught) { setError(caught instanceof Error ? caught.message : (english ? "We could not submit your complaint." : "Uw klacht kon niet worden verzonden.")); } finally { setBusy(false); } };
  const copy = english ? { eyebrow: "Customer care", title: "Tell us what happened", desc: "We take every complaint seriously. Share the details below so our team can follow up.", name: "Name", email: "Email", phone: "Phone (optional)", subject: "Subject", message: "Message", send: "Submit complaint", privacy: "Your details are used only to handle this complaint." } : { eyebrow: "Klantenservice", title: "Meld een probleem", desc: "We nemen elke klacht serieus. Deel hieronder de details zodat ons team kan opvolgen.", name: "Naam", email: "E-mail", phone: "Telefoon (optioneel)", subject: "Onderwerp", message: "Bericht", send: "Klacht versturen", privacy: "Uw gegevens worden alleen gebruikt om deze klacht te behandelen." };
  return <section className="border-t border-border bg-background py-16 sm:py-20" id="klacht"><div className="mx-auto grid max-w-7xl gap-10 px-5 sm:px-8 lg:grid-cols-[0.75fr_1.25fr] lg:gap-20"><div><p className="text-sm font-bold uppercase tracking-[0.16em] text-primary">{copy.eyebrow}</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-navy sm:text-4xl">{copy.title}</h2><p className="mt-4 text-lg leading-8 text-muted">{copy.desc}</p></div><form onSubmit={submit} className="border border-border bg-surface p-6 sm:p-8"><div className="hidden" aria-hidden="true"><label htmlFor="website">Website</label><input id="website" tabIndex={-1} autoComplete="off" value={values.website} onChange={(e) => set("website", e.target.value)} /></div><div className="grid gap-5 sm:grid-cols-2"><Field id="customerName" label={copy.name} value={values.customerName} onChange={set} required /><Field id="customerEmail" label={copy.email} type="email" value={values.customerEmail} onChange={set} required /><Field id="customerPhone" label={copy.phone} value={values.customerPhone} onChange={set} /><Field id="subject" label={copy.subject} value={values.subject} onChange={set} required /></div><label className="mt-5 block text-sm font-semibold text-navy" htmlFor="message">{copy.message}<textarea id="message" required maxLength={3000} rows={7} value={values.message} onChange={(e) => set("message", e.target.value)} className="mt-2 w-full rounded-xl border border-border bg-background p-3 text-base" /></label><p className="mt-4 text-sm text-muted">{copy.privacy}</p>{error ? <p role="alert" className="mt-4 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-800">{error}</p> : null}{result ? <p role="status" className="mt-4 rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-900">{result}</p> : null}<button type="submit" disabled={busy} className="mt-6 min-h-12 rounded-xl bg-primary px-6 py-3 text-base font-bold text-white hover:bg-navy disabled:opacity-50">{busy ? "…" : copy.send}</button></form></div></section>;
}
function Field({ id, label, type = "text", value, onChange, required = false }: { id: string; label: string; type?: string; value: string; onChange: (key: string, value: string) => void; required?: boolean }) { return <label className="block text-sm font-semibold text-navy" htmlFor={id}>{label}<input id={id} type={type} required={required} maxLength={id === "customerName" ? 100 : id === "customerEmail" ? 254 : id === "subject" ? 200 : 50} value={value} onChange={(e) => onChange(id, e.target.value)} className="mt-2 min-h-12 w-full rounded-xl border border-border bg-background px-3 text-base" /></label>; }
