"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";
import { requestPasswordReset, signIn, type Role } from "@/lib/auth-client";

export function BackofficeLogin({ expectedRole }: { expectedRole: Role }) {
  const owner = expectedRole === "site_owner";
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [forgot, setForgot] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(null); setMessage(null); try { if (forgot) { await requestPasswordReset(email, `${window.location.origin}/${owner ? "owner" : "backoffice"}/reset`); setMessage("Als dit account bestaat, is er een resetlink verstuurd."); } else { const session = await signIn(email, password); const role = session.user.app_metadata?.role; if (role !== "site_owner" && role !== "client_admin") throw new Error("Dit account heeft nog geen goedgekeurde backoffice-rol."); if (owner && role !== "site_owner") throw new Error("Dit account heeft geen toegang tot de site-owner omgeving."); window.location.href = owner ? "/owner" : "/backoffice"; } } catch (caught) { setError(caught instanceof Error ? caught.message : "Aanmelden is mislukt."); } finally { setBusy(false); } };
  return <main className="min-h-screen bg-background px-5 py-10 sm:px-8 sm:py-16"><div className="mx-auto max-w-md"><Link href="/" className="text-sm font-bold tracking-wide text-primary">Ster Schoonmaak</Link><div className="mt-8 border border-border bg-surface p-7 shadow-sm sm:p-9"><p className="text-sm font-bold uppercase tracking-[0.16em] text-primary">{owner ? "Site owner" : "Backoffice"}</p><h1 className="mt-3 text-3xl font-semibold tracking-tight text-navy">{forgot ? "Wachtwoord resetten" : "Veilig aanmelden"}</h1><p className="mt-3 text-base leading-7 text-muted">{owner ? "Beheer klachten en website-aanbiedingen." : "Bekijk en behandel klantklachten."}</p><form onSubmit={submit} className="mt-8 space-y-5"><div><label htmlFor="login-email" className="block text-sm font-semibold text-navy">E-mailadres</label><input id="login-email" type="email" required autoComplete="email" value={email} onChange={(e) => setEmail(e.target.value)} className="mt-2 min-h-12 w-full rounded-xl border border-border bg-background px-4 text-base outline-none focus:border-primary" /></div>{!forgot ? <div><label htmlFor="login-password" className="block text-sm font-semibold text-navy">Wachtwoord</label><input id="login-password" type="password" required autoComplete="current-password" value={password} onChange={(e) => setPassword(e.target.value)} className="mt-2 min-h-12 w-full rounded-xl border border-border bg-background px-4 text-base outline-none focus:border-primary" /></div> : null}{error ? <p role="alert" className="rounded-xl bg-red-50 px-4 py-3 text-sm text-red-800">{error}</p> : null}{message ? <p role="status" className="rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-900">{message}</p> : null}<button disabled={busy} className="min-h-12 w-full rounded-xl bg-primary px-5 py-3 text-base font-bold text-white hover:bg-navy disabled:opacity-50">{busy ? "Even geduld…" : forgot ? "Resetlink aanvragen" : "Aanmelden"}</button></form><div className="mt-6 flex flex-wrap gap-x-5 gap-y-2 text-sm"><button type="button" onClick={() => { setForgot((value) => !value); setError(null); setMessage(null); }} className="font-semibold text-primary underline">{forgot ? "Terug naar aanmelden" : "Wachtwoord vergeten?"}</button><Link href="/" className="text-muted underline">Naar website</Link></div></div></div></main>;
}
