"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { updatePassword } from "@/lib/auth-client";

export function PasswordReset() {
  const [token] = useState<string | undefined>(() => typeof window === "undefined" ? undefined : new URLSearchParams(window.location.hash.slice(1)).get("access_token") ?? undefined); const [password, setPassword] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (password.length < 8) { setError("Kies een wachtwoord van minstens 8 tekens."); return; } setBusy(true); setError(null); try { await updatePassword(password, token); setMessage("Je wachtwoord is bijgewerkt. Je kunt nu aanmelden."); } catch (caught) { setError(caught instanceof Error ? caught.message : "De resetlink is niet geldig."); } finally { setBusy(false); } };
  return <main className="min-h-screen bg-background px-5 py-10 sm:px-8 sm:py-16"><div className="mx-auto max-w-md"><Link href="/" className="text-sm font-bold tracking-wide text-primary">Ster Schoonmaak</Link><div className="mt-8 border border-border bg-surface p-7 shadow-sm sm:p-9"><p className="text-sm font-bold uppercase tracking-[0.16em] text-primary">Accountbeveiliging</p><h1 className="mt-3 text-3xl font-semibold text-navy">Nieuw wachtwoord</h1><form onSubmit={submit} className="mt-8 space-y-5"><div><label htmlFor="new-password" className="block text-sm font-semibold text-navy">Nieuw wachtwoord</label><input id="new-password" type="password" minLength={8} required autoComplete="new-password" value={password} onChange={(e) => setPassword(e.target.value)} className="mt-2 min-h-12 w-full rounded-xl border border-border bg-background px-4 text-base outline-none focus:border-primary" /></div>{error ? <p role="alert" className="rounded-xl bg-red-50 px-4 py-3 text-sm text-red-800">{error}</p> : null}{message ? <p role="status" className="rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-900">{message}</p> : null}<button disabled={busy || !token} className="min-h-12 w-full rounded-xl bg-primary px-5 py-3 text-base font-bold text-white disabled:opacity-50">{!token ? "Open de resetlink opnieuw" : busy ? "Even geduld…" : "Wachtwoord opslaan"}</button></form><Link href="/backoffice/login" className="mt-6 inline-block text-sm font-semibold text-primary underline">Terug naar aanmelden</Link></div></div></main>;
}
